print(len("eez"))
print("Hello World".index("o"))
print("Hello World!".count("l"))
print("Hello World"[3:7])
print("Hello World!"[3:7:1])
print("Hello World!"[3:8:2])
print("Hello World!"[::-1])
print("Hello World!".upper())
print("Hello World!".lower())
print("Hello World!".startswith("Hello"))
print("Hello World!".endswith("asdfasdf"))
print("Hello World!".split(" "))
